
name: tx_clients
channels:
    - pantheon
dependencies:
    - python ==2.7.10
    - twisted ==16.4.0
    - pyopenssl ==16.0.0
    - service_identity ==16.0.0
    - wrapt ==1.10.6
    - pylint
    - coverage
    - flake8
    - mock
    - pip:
        - bumpversion
